# One Hot Encoding

In [1]:
import pandas as pd

In [2]:
movie=pd.read_csv('IMDB Dataset.csv')

In [3]:
movie.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
len(movie['review'][0].split())

307

In [5]:
movie['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [6]:
movie.shape

(50000, 2)

In [9]:
# 50000 *300 ---> total words ---> 15 crore ---> corpus
# vocabulary ---> 2 crore
# vector ----> 3 croroe values

In [22]:
d=pd.DataFrame({'col': ['People Love AI', 'AI Love data', 'data Love Love', 'Love People People']})

In [23]:
d

                  col
0      People Love AI
1        AI Love data
2      data Love Love
3  Love People People

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
cv=CountVectorizer()

In [26]:
d['col']

0        People Love AI
1          AI Love data
2        data Love Love
3    Love People People
Name: col, dtype: str

In [27]:
cv.fit_transform(d['col']).toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 0, 1, 2]])

In [28]:
cv.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

In [29]:
cv=CountVectorizer(ngram_range=(2,2))

In [30]:
cv.fit_transform(d['col']).toarray()

array([[0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1]])

In [31]:
cv.vocabulary_

{'people love': 6,
 'love ai': 2,
 'ai love': 0,
 'love data': 3,
 'data love': 1,
 'love love': 4,
 'love people': 5,
 'people people': 7}

In [33]:
len(cv.vocabulary_)

8

In [32]:
d

                  col
0      People Love AI
1        AI Love data
2      data Love Love
3  Love People People

In [34]:
# bigram ---> 8
# unigram ---> 4
# trigram ---> 4
# unigram + bigram ---> 12
# unigram + bigram + trigram ---> 16

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
tf=TfidfVectorizer()

In [37]:
tf.fit_transform(d['col']).toarray()

array([[0.64043405, 0.        , 0.42389674, 0.64043405],
       [0.64043405, 0.64043405, 0.42389674, 0.        ],
       [0.        , 0.60276058, 0.7979221 , 0.        ],
       [0.        , 0.        , 0.31418628, 0.94936136]])

In [38]:
tf.get_feature_names_out()

array(['ai', 'data', 'love', 'people'], dtype=object)

In [39]:
tf.idf_

array([1.51082562, 1.51082562, 1.        , 1.51082562])