# Automated Data Cleaning

#### Types of Missing Data:

#### 1. Missing Completely at Random (MCAR)
#### 2. Missing At Random (MAR)
#### 3. Missing Not At Random (MNAR)

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

In [3]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [5]:
df['User ID'].isnull().sum()

np.int64(201)

In [6]:
df=df.drop(columns=['User ID'])

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

In [8]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [9]:
df[df['Heart Rate (BPM)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [18]:
## No pattern with any column for Heart Rate (BPM) null values, so it comes under 
# the category of Missing Completely at Random (MCAR)

In [16]:
### drop missing data --> dropna() ---> use only when the missing data is less 
# than 5% of the total data, otherwise it will lead to loss of information

### since overall null data is somwhere around 14% of the total data, we will not
#  drop the null values and instead find another way

In [17]:
### Mean/Median Imputation --> fill the missing data with the mean or median of 
# all rows of that data

### while going with mean value ---> check for outliers in the data, if there are
#  outliers then go with median value instead of mean value

In [19]:
### Age--->500(Outlier)---->1000--->mean---->??
### Age--->Median---->if you will arrange all values from low to high side
### Age--->Mode--->most frequently occuring value

In [20]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [21]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [22]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

In [24]:
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [25]:
df[df['Blood Oxygen Level (%)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [26]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.002867               97.841581   6985.685885
std           19.020902                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           75.220601               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [27]:
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

In [29]:
### Forward filling or backward filling  ----> time series data

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

In [31]:
df[df['Step Count'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,75.220601,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,75.220601,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

In [ ]:
### method ---> ffill() or bfill() ---> forward fill or backward fill

### error occured with 'method' so use .ffill() or .bfill() with the column name instead of the whole dataframe

df['Step Count'] = df['Step Count'].ffill()

In [35]:
df['Step Count'].isnull().sum()

np.int64(0)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

In [37]:
df['Sleep Duration (hours)'].value_counts()

Sleep Duration (hours)
ERROR                 247
7.167235622316564       1
6.538239375570314       1
7.367789630207228       1
8.378342673824589       1
                     ...
7.402748595032027       1
6.3821659358529015      1
6.91654920303435        1
5.691233932149209       1
5.691001039740254       1
Name: count, Length: 9604, dtype: int64

In [38]:
df[df['Sleep Duration (hours)']=='ERROR']

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
62,115.078288,99.928041,1918.372142,ERROR,Highly_Active,4
71,64.799778,94.743857,4613.859266,ERROR,Highly_Active,10
81,41.709895,96.857347,1413.015778,ERROR,Highly_Active,4
92,70.243810,97.171134,2336.583406,ERROR,Highly Active,7
...,...,...,...,...,...,...
9901,63.369107,96.229029,6656.786482,ERROR,Active,4
9912,75.933666,97.386073,1813.072248,ERROR,Sedentary,10
9927,87.579045,98.768633,3727.161872,ERROR,Active,1
9943,91.834863,96.145378,38831.465057,ERROR,Active,4
9951,70.335328,98.560133,1997.442874,ERROR,Highly_Active,9

In [39]:
### object type data ---> convert to numeric type data
### to_numeric()

In [40]:
df['Sleep Duration (hours)']=pd.to_numeric(df['Sleep Duration (hours)'], errors='coerce')

In [41]:
df[df['Sleep Duration (hours)']=='ERROR']

Empty DataFrame
Columns: [Heart Rate (BPM), Blood Oxygen Level (%), Step Count, Sleep Duration (hours), Activity Level, Stress Level]
Index: []

In [42]:
df['Sleep Duration (hours)'].dtype

dtype('float64')

In [43]:
df['Sleep Duration (hours)']

0       7.167236
1       6.538239
2            NaN
3       7.367790
4            NaN
          ...
9995    7.402749
9996    6.382166
9997    6.916549
9998    5.691234
9999    5.691001
Name: Sleep Duration (hours), Length: 10000, dtype: float64

In [44]:
df['Sleep Duration (hours)'].mean()

np.float64(6.505462918406444)

In [45]:
df['Sleep Duration (hours)'].median()

np.float64(6.503308362112644)

In [47]:
df['Sleep Duration (hours)']=df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [48]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(0)

In [49]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167236,Highly Active,1
1,75.220601,98.532195,727.601610,6.538239,Highly_Active,5
2,247.803052,97.052954,2826.521994,6.505463,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367790,Actve,3
4,61.950165,98.583797,15679.067648,6.505463,Highly_Active,6

In [50]:
### For categorical columns ---> Mode ---> Most frequently occuring value in your column

In [51]:
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: str

In [52]:
df['Activity Level'].isnull().sum()

np.int64(200)

In [53]:
df['Activity Level']=df['Activity Level'].fillna('Seddentary')

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 572.1 KB

In [55]:
### constant imputation ---> when you want to fill the missing values with the constant values like 'unknown'

In [56]:
df['Stress Level'].value_counts()

Stress Level
2            1007
7            1006
6            1001
3             995
1             984
9             976
4             966
10            954
5             945
8             917
Very High      49
Name: count, dtype: int64

In [57]:
### since very high value is required here we will go with constant imputation

In [58]:
df['Stress Level']=df['Stress Level'].fillna(5)

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(4), object(1), str(1)
memory usage: 560.0+ KB

In [61]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [63]:
df=df.drop(columns=['User ID'])

In [64]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')

In [65]:
df['Heart Rate (BPM)']=imputer.fit_transform(df[['Heart Rate (BPM)']])

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

In [67]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.002867               97.841581   6985.685885
std           19.020902                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           75.220601               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [68]:
imputer=SimpleImputer(strategy='mean')

In [69]:
df['Blood Oxygen Level (%)']=imputer.fit_transform(df[['Blood Oxygen Level (%)']])

In [70]:
imputer=SimpleImputer(strategy='most_frequent')

In [72]:
df['Activity Level']=imputer.fit_transform(df[['Activity Level']]).ravel()

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 734.1 KB

In [74]:
imputer=SimpleImputer(strategy='constant', fill_value=5)

In [76]:
df['Stress Level']=imputer.fit_transform(df[['Stress Level']]).ravel()

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(1), str(2)
memory usage: 722.0+ KB